module.exports = {
  COUNTRY : {
    INIT_COUNTRY: 'PEOPLE:INIT_COUNTRY',
    INIT_COUNTRY_SUCCESS: 'PEOPLE:INIT_COUNTRY_SUCCESS',
    INIT_COUNTRY_FAIL: 'PEOPLE:INIT_COUNTRY_FAIL',
    CHANGE_COUNTRY: 'PEOPLE:CHANGE_COUNTRY'
  },
  PEOPLE: {
    LOAD_PEOPLE_LIST: 'PEOPLE:LOAD_PEOPLE_LIST',
    LOAD_PEOPLE_LIST_SUCCESS: 'PEOPLE:LOAD_PEOPLE_LIST_SUCCESS',
    LOAD_PEOPLE_LIST_FAIL: 'PEOPLE:LOAD_PEOPLE_LIST_FAIL',
    LOAD_PERSON: 'PEOPLE:LOAD_PERSON',
    LOAD_PERSON_SUCCESS: 'PEOPLE:LOAD_PERSON_SUCCESS',
    LOAD_PERSON_FAIL: 'PEOPLE:LOAD_PERSON_FAIL'
  },
  ROUTE: {
    TRANSITION: 'ROUTE:TRANSITION'
  }
};